#pragma once

enum class E_ERROR_TYPE {
	NO_ERROR,
	INVALID_TOKEN,
	PARSING_PROBLEM,
	INVALID_NUMBER_OF_VALUES,
	INVALID_VALUE,
	TREE_CORRECTED,
	NOT_VARIABLE,
	NOT_FUNCTION,
	NOT_OPERATOR,
	NOT_NUMBER,
	INVALID_CHARACTERS,
};
